const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCTSBYCATEGORY: '/products/category',
  CATEGORIES: '/categories',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  VALIDATE_RESETCODE: '/validate-reset-code',
  ADMIN: '/admin/*',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PROFILE: '/profile',
  EDITPROFILE: '/profile-edit',
  PAYMENTRETURN: '/payment-return',
  ORDERS: '/my-orders',
  ORDERRETURN: '/order-return',
  REVIEW: '/review',
};

export default ROUTES;
